[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.steps]
- name = "Install PHP dependencies"
  command = "composer install --no-dev --optimize-autoloader"

- name = "Install Node.js dependencies"
  command = "npm ci"

- name = "Build assets"
  command = "npm run build"

- name = "Generate application key"
  command = "php artisan key:generate"

- name = "Run migrations"
  command = "php artisan migrate --force"

- name = "Cache configuration"
  command = "php artisan config:cache"

- name = "Cache routes"
  command = "php artisan route:cache"

- name = "Cache views"
  command = "php artisan view:cache" 